using SignalCut.Domain.Common;
using SignalCut.Domain.Enums;

namespace SignalCut.Domain.Entities;

public class Search : BaseEntity, ITenantEntity
{
    public Guid OrganizationId { get; set; }
    public Guid UserId { get; set; }
    public Guid? ProjectId { get; set; }

    public string RawQuery { get; set; } = string.Empty;
    public string ParsedTopicsJson { get; set; } = "[]"; // e.g. ["AI agents", "software engineering"]
    public string Intent { get; set; } = string.Empty;
    public int ResultCount { get; set; } = 0;

    // Navigation
    public virtual Organization Organization { get; set; } = null!;
    public virtual User User { get; set; } = null!;
    public virtual Project? Project { get; set; }
    public virtual ICollection<Source> Sources { get; set; } = new List<Source>();
}

public class Source : BaseEntity, ITenantEntity
{
    public Guid OrganizationId { get; set; }
    public Guid? SearchId { get; set; }
    public Guid? ProjectId { get; set; }

    public string ExternalSourceId { get; set; } = string.Empty;
    public string Provider { get; set; } = string.Empty; // "YouTube", "Podcast", "WebVideo", "UserUpload"
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Creator { get; set; } = string.Empty;
    public string Url { get; set; } = string.Empty;
    public DateTime? PublishedAt { get; set; }
    public double DurationSeconds { get; set; }
    public string ThumbnailUrl { get; set; } = string.Empty;
    public string Language { get; set; } = "en";
    public ContentType ContentType { get; set; } = ContentType.VIDEO;

    // Rights & Authorization (CRITICAL)
    public RightsStatus RightsStatus { get; set; } = RightsStatus.UNKNOWN;
    public AuthorizationStatus AuthorizationStatus { get; set; } = AuthorizationStatus.NOT_REQUIRED;
    public bool TranscriptAvailability { get; set; } = false;

    // Rights Confirmation Audit
    public Guid? RightsConfirmedByUserId { get; set; }
    public DateTime? RightsConfirmationTimestamp { get; set; }
    public string? RightsConfirmationStatement { get; set; }
    public string? RightsProofDocumentUrl { get; set; }

    // Relevance to Search
    public double RelevanceScore { get; set; } = 0.0;

    // Navigation
    public virtual Organization Organization { get; set; } = null!;
    public virtual Search? Search { get; set; }
    public virtual Project? Project { get; set; }
    public virtual ICollection<SourceItem> SourceItems { get; set; } = new List<SourceItem>();
    public virtual Transcript? Transcript { get; set; }
    public virtual ICollection<Moment> Moments { get; set; } = new List<Moment>();
    public virtual ICollection<MediaAsset> MediaAssets { get; set; } = new List<MediaAsset>();
}

public class SourceItem : BaseEntity
{
    public Guid SourceId { get; set; }
    public string ItemKey { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string MetadataJson { get; set; } = "{}";

    public virtual Source Source { get; set; } = null!;
}

public class Transcript : BaseEntity
{
    public Guid SourceId { get; set; }
    public string Language { get; set; } = "en";
    public string FullText { get; set; } = string.Empty;
    public int WordCount { get; set; }
    public bool IsAutoGenerated { get; set; } = true;
    public string Provider { get; set; } = "Whisper";

    // Navigation
    public virtual Source Source { get; set; } = null!;
    public virtual ICollection<TranscriptChunk> Chunks { get; set; } = new List<TranscriptChunk>();
}

public class TranscriptChunk : BaseEntity
{
    public Guid TranscriptId { get; set; }
    public int ChunkIndex { get; set; }
    public double StartTime { get; set; }
    public double EndTime { get; set; }
    public string Text { get; set; } = string.Empty;
    public string Speaker { get; set; } = string.Empty;
    public double Confidence { get; set; } = 1.0;

    // Navigation
    public virtual Transcript Transcript { get; set; } = null!;
}

public class Moment : BaseEntity, ITenantEntity
{
    public Guid OrganizationId { get; set; }
    public Guid SourceId { get; set; }

    public double StartTime { get; set; }
    public double EndTime { get; set; }
    public double DurationSeconds => EndTime - StartTime;

    public string TranscriptSnippet { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;

    // Moment scoring
    public double TopicRelevance { get; set; }
    public double HookStrength { get; set; }
    public double InformationDensity { get; set; }
    public double ClipScore { get; set; } // Overall composite score
    public double Confidence { get; set; } = 1.0;
    public string Speaker { get; set; } = string.Empty;

    public MomentObjective Objective { get; set; } = MomentObjective.Educational;

    // AI generated suggestions
    public string SuggestedHook { get; set; } = string.Empty;
    public string SuggestedTitle { get; set; } = string.Empty;
    public string SuggestedCaption { get; set; } = string.Empty;
    public string SuggestedDescription { get; set; } = string.Empty;
    public string SuggestedHashtagsJson { get; set; } = "[]";
    public string SuggestedCta { get; set; } = string.Empty;

    // Navigation
    public virtual Organization Organization { get; set; } = null!;
    public virtual Source Source { get; set; } = null!;
    public virtual ICollection<Clip> Clips { get; set; } = new List<Clip>();
}
