using SignalCut.Domain.Entities;
using SignalCut.Domain.Enums;

namespace SignalCut.Application.Interfaces;

public record SourceDiscoveryItem(
    string ExternalId,
    string Provider,
    string Title,
    string Description,
    string Creator,
    string Url,
    DateTime? PublishedAt,
    double DurationSeconds,
    string ThumbnailUrl,
    string Language,
    ContentType ContentType,
    RightsStatus RightsStatus,
    AuthorizationStatus AuthorizationStatus,
    bool TranscriptAvailability,
    double RelevanceScore
);

public interface ISourceProvider
{
    string ProviderName { get; }
    Task<IEnumerable<SourceDiscoveryItem>> SearchAsync(string query, int limit = 20, CancellationToken ct = default);
    Task<SourceDiscoveryItem?> GetMetadataAsync(string urlOrId, CancellationToken ct = default);
}

public interface ISearchProvider
{
    Task<(List<string> Topics, string Intent)> ParseQueryAsync(string query, CancellationToken ct = default);
    Task<IEnumerable<SourceDiscoveryItem>> SearchAllAsync(string query, int limit = 30, CancellationToken ct = default);
}

public record TranscriptResult(
    string FullText,
    string Language,
    int WordCount,
    List<TranscriptChunkResult> Chunks,
    bool IsAutoGenerated,
    string Provider
);

public record TranscriptChunkResult(
    int ChunkIndex,
    double StartTime,
    double EndTime,
    string Text,
    string Speaker,
    double Confidence
);

public interface ITranscriptProvider
{
    Task<TranscriptResult?> FetchExistingTranscriptAsync(string sourceUrl, CancellationToken ct = default);
}

public interface ISpeechToTextProvider
{
    Task<TranscriptResult> TranscribeAudioAsync(Stream audioStream, string language = "en", CancellationToken ct = default);
}

public interface IMediaProvider
{
    Task<Stream> DownloadMediaStreamAsync(string mediaUrl, CancellationToken ct = default);
    Task<Stream> ExtractAudioAsync(string mediaUrl, CancellationToken ct = default);
    Task<bool> ValidateUrlSafetyAsync(string mediaUrl);
}

public record MomentCandidate(
    double StartTime,
    double EndTime,
    string TranscriptSnippet,
    string Reason,
    double TopicRelevance,
    double HookStrength,
    double InformationDensity,
    double ClipScore,
    string Speaker,
    double Confidence,
    MomentObjective Objective,
    string SuggestedHook,
    string SuggestedTitle,
    string SuggestedCaption,
    string SuggestedDescription,
    List<string> SuggestedHashtags,
    string SuggestedCta
);

public interface ILanguageModelProvider
{
    string ProviderName { get; }
    Task<List<MomentCandidate>> FindMomentsAsync(string transcriptText, string topicQuery, MomentObjective objective, CancellationToken ct = default);
    Task<(string Hook, string Title, string Caption, string Description, List<string> Hashtags, string Cta)> GenerateCopyAsync(string momentTranscript, string contextTopic, CancellationToken ct = default);
}

public record RenderVideoRequest(
    Guid ClipId,
    string SourceVideoUrl,
    double StartTime,
    double EndTime,
    string AspectRatio, // 9:16, 1:1, 16:9
    int Width,
    int Height,
    bool HasWatermark,
    string CaptionStyle,
    string FontName,
    int FontSize,
    string PrimaryColorHex,
    string HighlightColorHex,
    string BackgroundColorHex,
    string? LogoUrl,
    bool ShowProgressBar,
    List<TranscriptChunkResult> Captions
);

public record RenderVideoResult(
    bool Success,
    string StorageKey,
    string StorageUrl,
    string? ThumbnailUrl,
    double DurationSeconds,
    string? ErrorMessage
);

public interface IVideoProcessor
{
    Task<RenderVideoResult> RenderClipAsync(RenderVideoRequest request, Action<int>? onProgress = null, CancellationToken ct = default);
}

public record PublishPostRequest(
    PublishingPlatform Platform,
    string EncryptedAccessToken,
    string? EncryptedRefreshToken,
    string VideoUrl,
    string Title,
    string Caption,
    List<string> Hashtags,
    DateTime? ScheduledAt
);

public record PublishPostResult(
    bool Success,
    string? ExternalPostId,
    string? ExternalPostUrl,
    string? ErrorMessage
);

public interface IPublishingProvider
{
    PublishingPlatform Platform { get; }
    Task<PublishPostResult> PublishAsync(PublishPostRequest request, CancellationToken ct = default);
}

public record PaymentCheckoutRequest(
    Guid OrganizationId,
    Guid UserId,
    decimal Amount,
    string Currency,
    decimal CreditsAmount,
    string SuccessUrl,
    string CancelUrl
);

public record PaymentCheckoutResult(
    string SessionId,
    string CheckoutUrl,
    string? ProviderOrderId
);

public record WebhookProcessResult(
    bool Handled,
    string? IdempotencyKey,
    decimal CreditsToAdd,
    Guid? OrganizationId,
    Guid? PaymentId,
    PaymentStatus Status,
    string? ErrorMessage
);

public interface IPaymentProvider
{
    PaymentProviderType ProviderType { get; }
    Task<PaymentCheckoutResult> CreateCheckoutSessionAsync(PaymentCheckoutRequest request, CancellationToken ct = default);
    Task<WebhookProcessResult> ProcessWebhookAsync(string payload, string signatureHeader, CancellationToken ct = default);
}

public interface IObjectStorage
{
    Task<string> UploadAsync(string key, Stream content, string contentType, CancellationToken ct = default);
    Task<Stream> DownloadAsync(string key, CancellationToken ct = default);
    Task<string> GetSignedUrlAsync(string key, TimeSpan expiresIn);
    Task<bool> DeleteAsync(string key, CancellationToken ct = default);
}
