using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SignalCut.Application.Common;
using SignalCut.Application.DTOs;
using SignalCut.Application.Interfaces;
using SignalCut.Domain.Entities;
using SignalCut.Domain.Enums;

namespace SignalCut.Application.Services;

public class MomentService : IMomentService
{
    private readonly IApplicationDbContext _context;
    private readonly ILanguageModelProvider _llmProvider;
    private readonly ITranscriptProvider _transcriptProvider;
    private readonly ICreditWalletService _creditWalletService;
    private readonly IRightsAuthorizationService _rightsAuthService;
    private readonly ILogger<MomentService> _logger;

    public MomentService(
        IApplicationDbContext context,
        ILanguageModelProvider llmProvider,
        ITranscriptProvider transcriptProvider,
        ICreditWalletService creditWalletService,
        IRightsAuthorizationService rightsAuthService,
        ILogger<MomentService> logger)
    {
        _context = context;
        _llmProvider = llmProvider;
        _transcriptProvider = transcriptProvider;
        _creditWalletService = creditWalletService;
        _rightsAuthService = rightsAuthService;
        _logger = logger;
    }

    public async Task<List<MomentDto>> DetectMomentsAsync(Guid organizationId, Guid userId, Guid sourceId, MomentObjective objective, CancellationToken ct = default)
    {
        var source = await _context.Sources
            .Include(s => s.Transcript)
                .ThenInclude(t => t!.Chunks)
            .FirstOrDefaultAsync(s => s.Id == sourceId && s.OrganizationId == organizationId, ct);

        if (source == null)
        {
            throw new NotFoundException(nameof(Source), sourceId);
        }

        // 1. CRITICAL: Strict Rights & Media Access Gate
        await _rightsAuthService.AssertCanEnterGenerationPipelineAsync(sourceId, ct);

        // 2. Cost control & Credit check (10 credits for AI Moment Analysis)
        const decimal requiredCredits = 10m;
        var wallet = await _creditWalletService.GetWalletAsync(organizationId, ct);
        if (wallet.AvailableBalance < requiredCredits)
        {
            throw new InsufficientCreditsException(requiredCredits, wallet.AvailableBalance);
        }

        // Generate synthetic JobId for credit tracking
        var jobId = Guid.NewGuid();
        await _creditWalletService.ReserveCreditsAsync(organizationId, requiredCredits, jobId, $"reserve-moments-{jobId}", ct);

        try
        {
            // 3. Ensure transcript is available from authorized media
            Transcript transcript;
            if (source.Transcript != null)
            {
                transcript = source.Transcript;
            }
            else
            {
                // Resolve authorized media target
                var mediaAsset = await _context.MediaAssets
                    .Where(m => m.SourceId == source.Id)
                    .OrderByDescending(m => m.CreatedAt)
                    .FirstOrDefaultAsync(ct);

                var targetMediaUrl = mediaAsset?.StorageUrl ?? source.Url;
                if (!string.IsNullOrEmpty(targetMediaUrl) && targetMediaUrl.StartsWith("/storage/"))
                {
                    var relative = targetMediaUrl.TrimStart('/').Replace('/', Path.DirectorySeparatorChar);
                    var localPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", relative);
                    if (File.Exists(localPath)) targetMediaUrl = localPath;
                }

                var fetched = await _transcriptProvider.FetchExistingTranscriptAsync(targetMediaUrl, ct);
                if (fetched == null || fetched.Chunks == null || fetched.Chunks.Count == 0)
                {
                    _logger.LogWarning("No transcript could be obtained from authorized media for source {SourceId} ('{Title}')", source.Id, source.Title);
                    throw new InvalidOperationException($"Unable to extract transcript from the authorized media for source '{source.Title}'. Real media transcript or caption data is required.");
                }

                transcript = new Transcript
                {
                    SourceId = source.Id,
                    Language = fetched.Language,
                    FullText = fetched.FullText,
                    WordCount = fetched.WordCount,
                    IsAutoGenerated = fetched.IsAutoGenerated,
                    Provider = fetched.Provider
                };

                foreach (var c in fetched.Chunks)
                {
                    transcript.Chunks.Add(new TranscriptChunk
                    {
                        ChunkIndex = c.ChunkIndex,
                        StartTime = c.StartTime,
                        EndTime = c.EndTime,
                        Text = c.Text,
                        Speaker = c.Speaker,
                        Confidence = c.Confidence
                    });
                }

                _context.Transcripts.Add(transcript);
                source.TranscriptAvailability = true;
                await _context.SaveChangesAsync(ct);
            }

            // 2. LLM Analysis: Detect moments with objective
            var candidates = await _llmProvider.FindMomentsAsync(transcript.FullText, source.Title, objective, ct);

            var createdMoments = new List<Moment>();
            foreach (var candidate in candidates)
            {
                var moment = new Moment
                {
                    OrganizationId = organizationId,
                    SourceId = source.Id,
                    StartTime = candidate.StartTime,
                    EndTime = candidate.EndTime,
                    TranscriptSnippet = candidate.TranscriptSnippet,
                    Reason = candidate.Reason,
                    TopicRelevance = candidate.TopicRelevance,
                    HookStrength = candidate.HookStrength,
                    InformationDensity = candidate.InformationDensity,
                    ClipScore = candidate.ClipScore,
                    Speaker = candidate.Speaker,
                    Confidence = candidate.Confidence,
                    Objective = candidate.Objective,
                    SuggestedHook = candidate.SuggestedHook,
                    SuggestedTitle = candidate.SuggestedTitle,
                    SuggestedCaption = candidate.SuggestedCaption,
                    SuggestedDescription = candidate.SuggestedDescription,
                    SuggestedHashtagsJson = System.Text.Json.JsonSerializer.Serialize(candidate.SuggestedHashtags),
                    SuggestedCta = candidate.SuggestedCta
                };
                createdMoments.Add(moment);
                _context.Moments.Add(moment);
            }

            // Commit credits
            await _creditWalletService.CommitReservedCreditsAsync(organizationId, jobId, requiredCredits, $"AI Moment Detection for '{source.Title}'", ct);

            // Record usage
            _context.UsageRecords.Add(new UsageRecord
            {
                OrganizationId = organizationId,
                UserId = userId,
                JobId = jobId,
                Provider = _llmProvider.ProviderName,
                Model = "default",
                Operation = "MOMENT_DETECTION",
                InputUnits = transcript.WordCount,
                OutputUnits = createdMoments.Count,
                EstimatedCost = 0.05m,
                ActualCost = 0.05m,
                CreditsDeducted = requiredCredits
            });

            await _context.SaveChangesAsync(ct);

            return createdMoments.Select(MapToDto).ToList();
        }
        catch
        {
            // Refund reservation on failure
            await _creditWalletService.RefundReservedCreditsAsync(organizationId, jobId, "Moment detection failed or was cancelled", ct);
            throw;
        }
    }

    public async Task<List<MomentDto>> GetMomentsBySourceAsync(Guid organizationId, Guid sourceId, CancellationToken ct = default)
    {
        var moments = await _context.Moments
            .Where(m => m.SourceId == sourceId && m.OrganizationId == organizationId)
            .OrderByDescending(m => m.ClipScore)
            .ToListAsync(ct);

        return moments.Select(MapToDto).ToList();
    }

    public async Task<MomentDto?> GetMomentByIdAsync(Guid organizationId, Guid momentId, CancellationToken ct = default)
    {
        var moment = await _context.Moments
            .FirstOrDefaultAsync(m => m.Id == momentId && m.OrganizationId == organizationId, ct);

        return moment != null ? MapToDto(moment) : null;
    }

    public async Task<MomentDto> RegenerateCopyAsync(Guid organizationId, Guid momentId, CancellationToken ct = default)
    {
        var moment = await _context.Moments
            .Include(m => m.Source)
            .FirstOrDefaultAsync(m => m.Id == momentId && m.OrganizationId == organizationId, ct);

        if (moment == null)
        {
            throw new NotFoundException(nameof(Moment), momentId);
        }

        var (hook, title, caption, desc, hashtags, cta) = await _llmProvider.GenerateCopyAsync(moment.TranscriptSnippet, moment.Source.Title, ct);

        moment.SuggestedHook = hook;
        moment.SuggestedTitle = title;
        moment.SuggestedCaption = caption;
        moment.SuggestedDescription = desc;
        moment.SuggestedHashtagsJson = System.Text.Json.JsonSerializer.Serialize(hashtags);
        moment.SuggestedCta = cta;
        moment.UpdatedAt = DateTime.UtcNow;

        await _context.SaveChangesAsync(ct);

        return MapToDto(moment);
    }

    private static MomentDto MapToDto(Moment m)
    {
        List<string> hashtags;
        try
        {
            hashtags = System.Text.Json.JsonSerializer.Deserialize<List<string>>(m.SuggestedHashtagsJson) ?? new List<string>();
        }
        catch
        {
            hashtags = new List<string>();
        }

        return new MomentDto(
            m.Id,
            m.SourceId,
            m.StartTime,
            m.EndTime,
            m.DurationSeconds,
            m.TranscriptSnippet,
            m.Reason,
            m.TopicRelevance,
            m.HookStrength,
            m.InformationDensity,
            m.ClipScore,
            m.Speaker,
            m.Objective,
            m.SuggestedHook,
            m.SuggestedTitle,
            m.SuggestedCaption,
            m.SuggestedDescription,
            hashtags,
            m.SuggestedCta
        );
    }
}
