using System.Net.Http.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SignalCut.Application.Interfaces;

namespace SignalCut.Infrastructure.Providers.Transcription;

public class TranscriptProvider : ITranscriptProvider
{
    private readonly HttpClient _httpClient;
    private readonly IConfiguration _config;
    private readonly ILogger<TranscriptProvider> _logger;

    public TranscriptProvider(
        HttpClient httpClient,
        IConfiguration config,
        ILogger<TranscriptProvider> logger)
    {
        _httpClient = httpClient;
        _config = config;
        _logger = logger;
    }

    public async Task<TranscriptResult?> FetchExistingTranscriptAsync(string sourceUrl, CancellationToken ct = default)
    {
        _logger.LogInformation("Attempting to fetch real transcript for URL: {Url}", sourceUrl);

        var workerUrl = _config["AI_WORKER_URL"] ?? "http://localhost:8000";

        try
        {
            var reqObj = new
            {
                sourceUrl,
                language = "en",
                detectSpeakers = true
            };

            using var reqMsg = new HttpRequestMessage(HttpMethod.Post, $"{workerUrl}/api/v1/transcription")
            {
                Content = JsonContent.Create(reqObj)
            };
            var apiKey = _config["AI_WORKER_API_KEY"];
            if (!string.IsNullOrWhiteSpace(apiKey))
            {
                reqMsg.Headers.Add("X-API-Key", apiKey);
            }

            var resp = await _httpClient.SendAsync(reqMsg, ct);
            if (resp.IsSuccessStatusCode)
            {
                var data = await resp.Content.ReadFromJsonAsync<WorkerTranscriptionResponseDto>(cancellationToken: ct);
                if (data != null && data.Chunks != null && data.Chunks.Count > 0)
                {
                    _logger.LogInformation("Successfully retrieved {Count} transcript chunks from AI Worker for {Url}", data.Chunks.Count, sourceUrl);
                    var mappedChunks = data.Chunks.Select(c => new TranscriptChunkResult(
                        c.ChunkIndex,
                        c.StartTime,
                        c.EndTime,
                        c.Text,
                        c.Speaker ?? "Speaker 1",
                        c.Confidence
                    )).ToList();

                    return new TranscriptResult(
                        data.FullText,
                        data.Language ?? "en",
                        data.WordCount > 0 ? data.WordCount : data.FullText.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length,
                        mappedChunks,
                        data.IsAutoGenerated,
                        data.Provider ?? "SignalCut-AI"
                    );
                }
            }
            else
            {
                _logger.LogWarning("AI worker transcription returned status code {Code} for {Url}", resp.StatusCode, sourceUrl);
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to connect to AI Worker for real transcription at {Url}", workerUrl);
        }

        return null;
    }

    private sealed record WorkerTranscriptionResponseDto(
        string FullText,
        string Language,
        int WordCount,
        List<WorkerChunkItemDto>? Chunks,
        bool IsAutoGenerated,
        string Provider
    );

    private sealed record WorkerChunkItemDto(
        int ChunkIndex,
        double StartTime,
        double EndTime,
        string Text,
        string Speaker,
        double Confidence
    );
}


public class SpeechToTextProvider : ISpeechToTextProvider
{
    public Task<TranscriptResult> TranscribeAudioAsync(Stream audioStream, string language = "en", CancellationToken ct = default)
    {
        var chunks = new List<TranscriptChunkResult>
        {
            new(0, 0, 15, "Transcribed speech segment from audio stream.", "Speaker 1", 0.98)
        };

        return Task.FromResult(new TranscriptResult(
            "Transcribed speech segment from audio stream.",
            language,
            7,
            chunks,
            true,
            "Whisper"
        ));
    }
}
